name = "QuackStack"
description = "Software Development Team"
keywords = "QuackStack, software, web, development, dev"
image = "jason-richard-VTvnoNBowZs-unsplash.webp"
theme = "dark"
primary_color = "#a5a127"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://gdamaso.github.io/QuackStack/"

[[sections]]
title = "Team Members"
description = "Learn more about our developers"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Kent"
description = "Full Stack Developer"
url = "https://kcaparas-portfolio.web.app/"
[[sections.items]]
title = "David"
description = "User Experience Developer"
url = "https://www.linkedin.com/in/david-goodfellow-2ba0232b5/"
[[sections.items]]
title = "Gui"
description = "Full Stack Developer"
url = "https://gdamaso.github.io/GDamaso/"

[[sections]]
title = "Our Project"
description = "Test our berries nutrient calculator"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "BetterBerries"
url = "https://better-berries-test.apps.silver.devops.gov.bc.ca/"
# [[sections.items]]
# title = "IMDb"
# url = "https://www.imdb.com/name/nm0350453/"
# [[sections.items]]
# title = "Wikipedia"
# url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
# [[sections.items]]
# title = "Rotten Tomatoes"
# url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
